version: '3.3'
services:
  xuexi:
    image: techxuexi/techxuexi-arm64v8:latest
    container_name: xuexi
    restart: always
    volumes:
      - "D:\OneDrive - Stanford University - Danny Live@Edu Test\Documents\opt\xuexi\user:/xuexi/user"
    shm_size: 2gb
    environment:
      - "CRONTIME=20 8,20 * * *"
      - "ZhuanXiang=false"
      - "Pushmode=1"
      - "AccessToken=d9a3f1c7e410059c036cbb7177085ae5287231ac3da54dbce480f0b35e74cc00"
      - "Secret=SEC9e4eba5b30205f76a286277e569f7e85bc111b171a9e4991dd6eddf768915015"
      - "Scheme=dtxuexi://appclient/page/study_feeds?url="
  ql:
    container_name: ql
    restart: always
    volumes:
      - D:\OneDrive - Stanford University - Danny Live@Edu Test\Documents\opt\ql\data:/ql/data
    ports:
      - "5700:5700"
    image: whyour/qinglong