version: '3.3'
services:
  mysql:
    container_name: mysql
    restart: always
    volumes:
      - '/opt/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - '/out/mysql/:/out/mysql/'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: biarms/mysql:5.7.30-linux-arm64v8
  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '/opt/config/redis.conf:/etc/redis/redis.conf'
      - '/out/data:/data'
    command: redis-server /etc/redis/redis.conf --requirepass HBQ521521cf* --appendonly yes
    image: redis:5.0.3
  mongo:
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    image: mongo
  minio:
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '/opt/minio/data:/data'
      - '/opt/minio/config:/root/.minio'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=HBQ521521cf*
    command: server /data --console-address ":9001" --address ":9000"
    image: minio/minio
  nginx:
    container_name: nginx
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - '/opt/config/nginx.conf:/etc/nginx/nginx.conf'
      - '/opt/cert:/etc/nginx/cert'
      - '/opt/minio/data/dev-ui:/etc/nginx/dev-ui'
    image: nginx:1.13
  alist:
    container_name: alist
    restart: always
    volumes:
      - '/opt/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    image: xhofe/alist:latest
  hui:
    container_name: hui
    restart: always
    ports:
      - '81:8080'
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx1g
      - ALIYUNDRIVE_REFRESH_TOKEN=0586e5ff2f944361adcbbd5dc0ad49d4
      - ALIYUNDRIVE_AUTH_PASSWORD=HBQ521521cf*
    volumes:
      - '/etc/localtime:/etc/localtime'
    image: baoqihui/webdav-aliyundriver
  xue:
    container_name: xue
    restart: always
    ports:
      - '81:8080'
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx1g
      - ALIYUNDRIVE_REFRESH_TOKEN=0586e5ff2f944361adcbbd5dc0ad49d4
      - ALIYUNDRIVE_AUTH_PASSWORD=HBQ521521cf*
    volumes:
      - '/etc/localtime:/etc/localtime'
    image: baoqihui/webdav-aliyundriver
